### ISSUE TITLE
Camera / audio is still in use even after the stage is closed or leave

### ISSUE THREAD

**Issue by rameshvoltella** [aws-samples/amazon-ivs-real-time-for-android-demo#9]
Hi,

i am using the demo app and its working fine only one issue we noticed during the testing, the camera / audio is till in use even after we leave the stage i am using the basic broadcast sample and then while testing our tester found even after we exit or leave the call the camera/audio is in access, the problem is in the sample ([sample code](https://github.com/aws-samples/amazon-ivs-broadcast-android-sample/tree/main)) also. How we tested is that after leaving the stage and backpress and closed the stage activity, After that  we open phone camera or screen recorder and try to record a video then the system showing we cant record voice as its used by our app, so after destring the app completely from task bar we were able to record the video with sound, So please help to solve this issue.

on destroy we used the following codes
  ```
 override fun onDestroy() {
        clearPreview()
        leaveStage()
        viewModel.release()
        super.onDestroy()
    }
```

clearPreview()

  ```
private fun clearPreview() {
        binding.participantListLayout.removeAllViews()
        binding.opponentView.removeAllViews()
        binding.userView.removeAllViews()
    }
```

 leaveStage()

```
   private fun leaveStage() {
        viewModel.leaveStage()

    }
```
@mboulin Please give a help as we are at deadline of our release

**Comment by mboulin** [comment]
The issue you are facing is likely due to the camera and microphone resources not being properly released after leaving the stage.

Could you try releasing the DeviceDiscovery instance: The `DeviceDiscovery` class manages the local device resources like camera and microphone. You should release this instance when you are done using it. Add the following line in your `onDestroy()` method:

```
override fun onDestroy() {
    clearPreview()
    leaveStage()
    viewModel.release()
    deviceDiscovery?.release() // Add this line
    deviceDiscovery = null // And this line
    super.onDestroy()
}
```

You may try to also release the Stage instance in your leaveStage() method.
